
'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Return the letter that was added to t.
'''
def difference(s,t):
    count={}

    for ch in s:
        if ch in count:
            count[ch]+=1
        else:
            count[ch]=1

    for ch in t:
        if ch in count:
            count[ch]-=1
        else:
            return ch
        
        if count[ch]<0:
            return ch
        
    return None 
        
        
print(difference('leetcode','leetcodee'))

'''
Time Complexity: O(n)
space complexity: O(n)
'''

